language: python
python:
  - "3.4"
# # command to run tests
script: python setup.py test
before_deploy:
  - pip install s3pypi
deploy:
  provider: script
  script: bin/deploy
  on:
    branch: master
